apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-aws
  namespace: default
spec:
  podIdentity:
    provider: aws-eks

---

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: comfyui-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: comfyui
    kind: Deployment
    apiVersion: apps/v1
  pollingInterval: 10  # in seconds
  cooldownPeriod: 300  # in seconds
  minReplicaCount: 0
  maxReplicaCount: 1
  triggers:
    - type: aws-sqs-queue
      authenticationRef:
        name: keda-trigger-auth-aws
      metadata:
        queueURL: https://sqs.eu-west-2.amazonaws.com/339712991492/wedgwood-ai-staging-queue
        queueLength: '3'  # Number of messages per replica
        awsRegion: eu-west-2
